project:
  type: book

book:
  title: "quartoBook - Learning Git"
  author: "Alex Boyle"
  date: "7/18/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - PAT.qmd
    - Connect.qmd
    - Detect.qmd
    - newproj.qmd
    - commands.qmd
    - pullrequests.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

