---
title: "Detect Git from RStudio"
---

If you want RStudio to help with your Git and GitHub work, it must be able to find the Git executable.

This usually “just works”, so this page is aimed at people who have reason to suspect they have a problem.

This is something you set up once-per-computer.

## **Do you have a problem?**

Let’s check if RStudio can find the Git executable.

-   *File \> New Project…* Do you see an option to create from Version Control? If yes, good.

-   Select *New Directory* \> *Empty Project*. Do you see a checkbox “Create a git repository”? If yes, good, CHECK IT.

Keep reading if things don’t go so well or you want to know more.

## **Find Git yourself**

RStudio can only act as a GUI front-end for Git if Git has been successfully installed  **AND RStudio can find it**.

A basic test for successful installation of Git is to simply enter `git` in the shell (Appendix [A](https://happygitwithr.com/shell#shell)). If you get a complaint about Git not being found, it means installation was unsuccessful or that it is not being found, i.e. it is not on your `PATH`.

If you are not sure where the Git executable lives, try this in a shell:

-   `which git` (Mac, Linux, Git Bash shell on Windows)

-   `where git` (Windows command prompt, i.e. `cmd.exe`)

## **Tell RStudio where to find Git**

If Git appears to be installed and findable, launch RStudio. Quit and re-launch RStudio if there’s **any doubt in your mind** about whether you opened RStudio before or after installing Git. Don’t make me stop this car and restart RStudio for you in office hours. DO IT.

From RStudio, go to *Tools \> Global Options \> Git/SVN* and make sure that the box *Git executable* points to your Git executable.

On macOS and Linux, the path usually looks something like this:

``` bash
/usr/bin/git
```

If you need to set this on macOS, it can sometimes be hard to navigate to the necessary directory, once you’ve clicked “Browse” and are working with a Finder-type window. The keyboard shortcut “command + shift + g” will summon “Go To Folder”, where you will be able to type or paste any path you want.
